export const tableContent = [
    {
        id: 0,
        name: "Sophia Turner",
        email: "sophiaturner@example.com",
        phoneNumber: "(555) 123-4567",
        role: "Administrador",
        status: "Ativo",
    },
    {
        id: 1,
        name: "Liam Johnson",
        email: "liamjohnson87@example.com",
        phoneNumber: "(555) 432-1098",
        role: "Administrador",
        status: "Ativo",
    },
    {
        id: 2,
        name: "Olivia Smith",
        email: "oliviasmith12@example.com",
        phoneNumber: "(555) 876-5432",
        role: "Participante",
        status: "Pendente",
    },
    {
        id: 3,
        name: "Noah Brown",
        email: "noahbrown576@example.com",
        phoneNumber: "(555) 456-7890",
        role: "Organizador",
        status: "Banido",
    },
    {
        id: 4,
        name: "Emma Davis",
        email: "emmadavis25@example.com",
        phoneNumber: "(555) 234-5678",
        role: "Organizador",
        status: "Ativo",
    },
    {
        id: 5,
        name: "Sophia Turner",
        email: "sophiaturner@example.com",
        phoneNumber: "(555) 123-4567",
        role: "Administrador",
        status: "Ativo",
    },
    {
        id: 6,
        name: "Liam Johnson",
        email: "liamjohnson87@example.com",
        phoneNumber: "(555) 432-1098",
        role: "Administrador",
        status: "Ativo",
    },
    {
        id: 7,
        name: "Olivia Smith",
        email: "oliviasmith12@example.com",
        phoneNumber: "(555) 876-5432",
        role: "Participante",
        status: "Pendente",
    },
    {
        id: 8,
        name: "Noah Brown",
        email: "noahbrown576@example.com",
        phoneNumber: "(555) 456-7890",
        role: "Organizador",
        status: "Banido",
    },
    {
        id: 9,
        name: "Emma Davis",
        email: "emmadavis25@example.com",
        phoneNumber: "(555) 234-5678",
        role: "Organizador",
        status: "Ativo",
    },
];
